apiVersion: v1
entries:
  stress-test-addons:
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-16T19:21:18.4750036-05:00"
    description: Baseline resources and templates for stress testing clusters
    digest: e83aa9490e2afa1c3917fb31b4cf4594414ee52d2b7182104bd84d9e1b7b860f
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-16T19:12:06.7987473-05:00"
    description: Baseline resources and templates for stress testing clusters
    digest: a275a234ab853fb4f88f54b58a29c7de756cb677eca3b316f73daed147ee0f97
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-04T16:31:20.7093854-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: f9d7efb5ec1c2600b75ca3186445e31559ec1a8f48e3d8903ed3a5f74052f6ba
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-04T12:36:04.1904091-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: a0e3d266ea86088ad9679a862745542aad9320c654d25bcf7d7ad360513925ac
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-09-27T15:06:23.276703-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 845aa5a30d334442f8e1f1a48150789022585586ec4be3e42ee2a40a96020ce6
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-09-24T17:01:27.6168346-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 8c775cda83c851f4465c6b5dd575d5b7ddc26d01dd1d6308d8247ec7c411b015
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-11T19:44:41.2835291-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 482c089b6181a17b1de3c741b8d503582af1d7ac93b13076f05d1bbf70ab5981
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-10T12:25:32.7932615-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 40c564cf2fdc37d4cccdd8529b4df0a4f4acabb4d81f9e86d738e7a88cd26081
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-07-30T07:38:55.4331073-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 8adc1ae609fda0d0c4c54937876363ac97979485ac2802884409e67e207327b0
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-07-28T22:21:27.6697515-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: cce228906811f1b39db7bcd031c94192751caa0a94f7c6035e21e3de8fc5858d
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.2.tgz
    version: 0.1.2
generated: "2021-11-16T19:21:18.4744262-05:00"
