apiVersion: v1
entries:
  stress-test-addons:
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-13T17:23:40.9241683-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 2e0e076ca62ea57d05624e74880717e7edf0cbeda4d878132344702b376c3b71
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-11T19:44:41.2835291-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 482c089b6181a17b1de3c741b8d503582af1d7ac93b13076f05d1bbf70ab5981
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-10T12:25:32.7932615-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 40c564cf2fdc37d4cccdd8529b4df0a4f4acabb4d81f9e86d738e7a88cd26081
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-07-30T07:38:55.4331073-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 8adc1ae609fda0d0c4c54937876363ac97979485ac2802884409e67e207327b0
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-07-28T22:21:27.6697515-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: cce228906811f1b39db7bcd031c94192751caa0a94f7c6035e21e3de8fc5858d
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.2.tgz
    version: 0.1.2
generated: "2021-08-13T17:23:40.9233485-04:00"
