apiVersion: v1
entries:
  stress-test-addons:
  - apiVersion: v2
    appVersion: v0.1
    created: "2023-09-22T16:48:47.835082288-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 73d86e156b1f87d556ef3d51d048bb55f3f864867c9a422f0fd67bbc36a14c11
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: v0.1
    created: "2023-09-21T14:55:43.2096162-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 25da269ff8138e080a7703dcfb9833d6d772cb18470ef82262c4890c8b63eeda
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.1
    created: "2023-09-14T17:52:24.713925164-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: e8f8be8636ded8171f80aef32599fc4351d393470ef9f2143e692b0588473acb
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-10-21T13:08:46.8348009-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 6d81c04227b3195135a70163cba43ea11e9ea336ff4e59158ad8795996f08c6c
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-10-21T10:48:59.6509142-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: d8b05f5908882db719031917555b624435a71c08d3405e4e418d6aff1660116c
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.21.tgz
    version: 0.1.21
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-10-21T10:47:38.21951-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 3bf2c2e205525637053c27597212cebd180336bb1825d26902ce4d89f161f9bd
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.20.tgz
    version: 0.1.20
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-06-30T15:09:19.3110544-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: b8248b376dba388aec32a77ec5ba8fd76b59b7fa0916c83b924466bc77280af4
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.19.tgz
    version: 0.1.19
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-06-29T18:40:52.9995426-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: c579efd3868e48b0ab40a22335e16de67ea6361e394c09e4f589154b068a7060
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.18.tgz
    version: 0.1.18
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-05-17T21:25:11.1546837-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 8b99f79f770e655d63710b1332cd5b09827c8780030e1d43ca50b1463e53ae58
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.17.tgz
    version: 0.1.17
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-04-15T16:00:43.4512334-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 4573bd063182030f8cd39a4ae0fc31abf03f642bed41721a3abc41ac315ba65f
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.16.tgz
    version: 0.1.16
  - apiVersion: v2
    appVersion: v0.1
    created: "2022-03-22T19:16:14.3599204-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: bc56677a0218bc7cf7a2d709da8dd2291ae160737a6c53d859de98c488cb1990
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-12-02T17:54:52.7194418-05:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 1e944bd23f2a7697d539d06abdc6216ac1549e2a29d65752442aef3e4286f38a
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.13.tgz
    version: 0.1.13
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-16T19:21:18.4750036-05:00"
    description: Baseline resources and templates for stress testing clusters
    digest: e83aa9490e2afa1c3917fb31b4cf4594414ee52d2b7182104bd84d9e1b7b860f
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-16T19:12:06.7987473-05:00"
    description: Baseline resources and templates for stress testing clusters
    digest: a275a234ab853fb4f88f54b58a29c7de756cb677eca3b316f73daed147ee0f97
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-04T16:31:20.7093854-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: f9d7efb5ec1c2600b75ca3186445e31559ec1a8f48e3d8903ed3a5f74052f6ba
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-11-04T12:36:04.1904091-07:00"
    description: Baseline resources and templates for stress testing clusters
    digest: a0e3d266ea86088ad9679a862745542aad9320c654d25bcf7d7ad360513925ac
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-09-27T15:06:23.276703-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 845aa5a30d334442f8e1f1a48150789022585586ec4be3e42ee2a40a96020ce6
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-09-24T17:01:27.6168346-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 8c775cda83c851f4465c6b5dd575d5b7ddc26d01dd1d6308d8247ec7c411b015
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-11T19:44:41.2835291-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 482c089b6181a17b1de3c741b8d503582af1d7ac93b13076f05d1bbf70ab5981
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-08-10T12:25:32.7932615-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 40c564cf2fdc37d4cccdd8529b4df0a4f4acabb4d81f9e86d738e7a88cd26081
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-07-30T07:38:55.4331073-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: 8adc1ae609fda0d0c4c54937876363ac97979485ac2802884409e67e207327b0
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v0.1
    created: "2021-07-28T22:21:27.6697515-04:00"
    description: Baseline resources and templates for stress testing clusters
    digest: cce228906811f1b39db7bcd031c94192751caa0a94f7c6035e21e3de8fc5858d
    name: stress-test-addons
    urls:
    - https://stresstestcharts.blob.core.windows.net/helm/stress-test-addons-0.1.2.tgz
    version: 0.1.2
generated: "2023-09-22T16:48:47.827726695-04:00"
