env: test
appInsightsKeySecretName:
  pg: appInsightsInstrumentationKey-4kuek4dgiq7vo
  prod: appInsightsInstrumentationKey-tj6foiiklcb3m
  dev: ""
  storage: appInsightsInstrumentationKey-lkxxtjuf245tm
appInsightsConnectionStringSecretName:
  pg: appInsightsConnectionString-4kuek4dgiq7vo
  prod: appInsightsConnectionString-tj6foiiklcb3m
  dev: ""
  storage: appInsightsConnectionString-lkxxtjuf245tm
debugStorageKeySecretName:
  pg: debugStorageKey-4kuek4dgiq7vo
  prod: debugStorageKey-tj6foiiklcb3m
  dev: ""
  storage: debugStorageKey-lkxxtjuf245tm
debugStorageAccountSecretName:
  pg: debugStorageAccount-4kuek4dgiq7vo
  prod: debugStorageAccount-tj6foiiklcb3m
  dev: ""
  storage: debugStorageAccount-lkxxtjuf245tm
debugFileShareName:
  pg: stressfiles4kuek4dgiq7vo
  prod: stressfilestj6foiiklcb3m
  dev: ""
  storage: stressfileslkxxtjuf245tm
staticTestSecretsKeyvaultName:
  pg: stress-secrets-pg
  prod: stress-secrets-prod
  dev: ""
clusterTestSecretsKeyvaultName:
  pg: stress-kv-4kuek4dgiq7vo
  prod: stress-kv-tj6foiiklcb3m
  dev: ""
  storage: stress-kv-lkxxtjuf245tm
secretProviderIdentity:
  pg: 34c8068f-ed92-4406-aeef-6bd22b5c5514
  prod: 3ecc5fb1-bebc-4a72-8d6e-49597681796d
  dev: ""
  storage: ac866d4a-5c9c-4421-bff9-49c7c977df1a
provisionerAppId:
  pg: e3fdf864-b936-4279-b787-55adc0f9984a
  prod: 5d3c637e-07b7-4b29-83d9-87eb050dfdfb
  dev: ""
infraWorkloadAppServiceAccountName:
  pg: workload-svc
  prod: workload-svc
  dev: ""
  storage: workload-svc
infraWorkloadAppClientId:
  pg: 3f0eb782-ba84-45a5-abfd-be810e109a41
  prod: 19c8d842-8c93-4646-858b-e75607939368
  dev: ""
  storage: 2fb25652-3933-45ed-a462-e588b9726b29
infraWorkloadAppObjectId:
  pg: 62bfa80b-2b8d-4bcd-b50c-20db05e0ba60
  prod: 2d1d5aa0-7450-466d-b97c-a74124c43f52
  dev: ""
  storage: 6f896977-3bca-43b6-9f77-ac8f647b9dc6
workloadAppClientNamePool:
  pg: stress-app-workload-pg-0,stress-app-workload-pg-1,stress-app-workload-pg-2,stress-app-workload-pg-3,stress-app-workload-pg-4
  prod: stress-app-workload-prod-0,stress-app-workload-prod-1,stress-app-workload-prod-2,stress-app-workload-prod-3,stress-app-workload-prod-4
  dev: 
  storage: stress-app-workload-storage-0,stress-app-workload-storage-1,stress-app-workload-storage-2,stress-app-workload-storage-3,stress-app-workload-storage-4
workloadAppIssuer:
  pg: https://westus3.oic.prod-aks.azure.com/70a036f6-8e4d-4615-bad6-149c02e7720d/8aa0bb26-05cc-43b8-a4fc-026f539c94e3/
  prod: https://westus2.oic.prod-aks.azure.com/70a036f6-8e4d-4615-bad6-149c02e7720d/11a94e1a-8b07-45e4-87f3-2fccbc96937d/
  dev: 
  storage: https://southcentralus.oic.prod-aks.azure.com/70a036f6-8e4d-4615-bad6-149c02e7720d/51ab5b08-e986-4388-a81a-0ab22fed9736/
clusterGroup:
  pg: SSS3PT_rg-stress-cluster-pg
  prod: SSS3PT_rg-stress-cluster-prod
  dev: 
  storage: SSS3PT_rg-stress-cluster-storage
subscription:
  pg: public
  prod: public
  dev: public
subscriptionId:
  pg: 4d042dc6-fe17-4698-a23f-ec6a8d1e98f4
  prod: 4d042dc6-fe17-4698-a23f-ec6a8d1e98f4
  dev: 
  storage: 4d042dc6-fe17-4698-a23f-ec6a8d1e98f4
tenantId:
  pg: 70a036f6-8e4d-4615-bad6-149c02e7720d
  prod: 70a036f6-8e4d-4615-bad6-149c02e7720d
  dev: ""
  storage: 70a036f6-8e4d-4615-bad6-149c02e7720d

