emit:
  - "@typespec/json-schema"
options:
  "@typespec/json-schema":
    file-type: "json"
    emitter-output-dir: "{project-root}"
    emitAllModels: false
    emitAllRefs: false
  "@azure-tools/typespec-python":
    package-dir: "apiview-stub-generator"
    package-name: "treestyle-parser"
    emitter-output-dir: "{project-root}/../../../../packages/python-packages/apiview-stub-generator/apistub/_generated"
    namespace: "treestyle.parser"
    package-version: 0.3.23
    generate-packaging-files: false
    generate-test: false
    generate-sample: false