repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-tabulate, types-PyYAML]   # example stubs
        files: tools/sdk-ai-bots/azure-sdk-qa-bot-evaluation/
        args: [--config-file=tools/sdk-ai-bots/azure-sdk-qa-bot-evaluation/pyproject.toml]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright
        files: tools/sdk-ai-bots/azure-sdk-qa-bot-evaluation/
        args: [--project=tools/sdk-ai-bots/azure-sdk-qa-bot-evaluation/pyrightconfig.json]
