apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: stress-file-share-kv-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    # Storage account information used for kubernetes fileshare volume mounting via the azure files csi driver
    # See https://docs.microsoft.com/azure/aks/azure-files-volume#create-a-kubernetes-secret
    # See https://docs.microsoft.com/azure/aks/azure-files-csi
    - secretName: debugstorageaccountconfig
      type: Opaque
      data:
        - objectName: {{ get .Values.debugStorageKeySecretName .Values.env }}
          key: azurestorageaccountkey
        - objectName: {{ get .Values.debugStorageAccountSecretName .Values.env }}
          key: azurestorageaccountname
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ get .Values.secretProviderIdentity .Values.env }}  # az vmss identity show ...
    keyvaultName: {{ get .Values.clusterTestSecretsKeyvaultName .Values.env }}
    objects:  |
      array:
        - |
          objectName: {{ get .Values.debugStorageKeySecretName .Values.env }}
          objectType: secret
        - |
          objectName: {{ get .Values.debugStorageAccountSecretName .Values.env }}
          objectType: secret
    tenantId: {{ get .Values.tenantId .Values.env }}
